<?php


class Athor extends Person
{
    public $id;
    public $name;
    public $idBook;
    public $description;

    /**
     * @return mixed
     */
    public function getName()
    {
        return parent::getName(); // TODO: Change the autogenerated stub
    }
}