<?php


class Librarian extends Person
{
    /**
     * Librarian constructor.
     * @param $object
     */
    public function __construct($object)
    {
        parent::__construct($object);
    }

    /**
     * @return mixed
     */
    public function getName()
    {
        return parent::getName(); // TODO: Change the autogenerated stub
    }

    /**
     * @return mixed
     */
    public function getBirthday()
    {
        return parent::getBirthday(); // TODO: Change the autogenerated stub
    }

    /**
     * @return mixed
     */
    public function getEmail()
    {
        return parent::getEmail(); // TODO: Change the autogenerated stub
    }

    /**
     * @return mixed
     */
    public function getPhone()
    {
        return parent::getPhone(); // TODO: Change the autogenerated stub
    }

    /**
     * @return mixed
     */
    public function getClass()
    {
        return parent::getClass(); // TODO: Change the autogenerated stub
    }

    /**
     * @param $phone
     * @return mixed
     */
    public function setPhone($phone)
    {
        return parent::setPhone($phone); // TODO: Change the autogenerated stub
    }

    /**
     * @param $email
     * @return mixed\
     */
    public function setEmail($email)
    {
        return parent::setEmail($email); // TODO: Change the autogenerated stub
    }

    /**
     * @param $birthday
     * @return mixed
     */
    public function setBirthday($birthday)
    {
        return parent::setBirthday($birthday); // TODO: Change the autogenerated stub
    }

    /**
     * @param $class
     * @return mixed
     */
    public function setClass($class)
    {
        return parent::setClass($class); // TODO: Change the autogenerated stub
    }

    /**
     * @param $name
     * @return mixed
     */
    public function setName($name)
    {
        return parent::setName($name); // TODO: Change the autogenerated stub
    }
}